"""empty message

Revision ID: e68a81f738f4
Revises: 0c7533763fa2
Create Date: 2026-06-06 11:43:26.278361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = 'e68a81f738f4'
down_revision: Union[str, Sequence[str], None] = '0c7533763fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_insert_buildings_history = PGFunction(
        schema="public",
        signature="insert_buildings_history()",
        definition='RETURNS trigger\n        LANGUAGE plpgsql\n        AS $function$\n        DECLARE\n        BEGIN\n            NEW."version" := COALESCE(NEW."version", 0) + 1;\n\n            INSERT INTO buildings_history (\n                building_id,    "version",      created_at,\n                updated_at,     address,        code,\n                district,       latitude,       longitude,\n                status_code,    finishing_code, metro,\n                metro_car,      metro_walk,     floors,\n                flats,          vvod,           anons_texts,\n                family_hypotec, county,         notes\n            ) VALUES (\n                NEW.building_id,    NEW."version",      NEW.created_at,\n                NEW.updated_at,     NEW.address,        NEW.code,\n                NEW.district,       NEW.latitude,       NEW.longitude,\n                NEW.status_code,    NEW.finishing_code, NEW.metro,\n                NEW.metro_car,      NEW.metro_walk,     NEW.floors,\n                NEW.flats,          NEW.vvod,           NEW.anons_texts,\n                NEW.family_hypotec, NEW.county,         NEW.notes\n            );\n\n            RETURN NEW;\n        END;\n        $function$'
    )
    op.create_entity(public_insert_buildings_history)

    public_insert_new_aparts_history = PGFunction(
        schema="public",
        signature="insert_new_aparts_history()",
        definition='RETURNS trigger\n        LANGUAGE plpgsql\n        AS $function$\n        DECLARE \n        BEGIN\n            NEW."version" := COALESCE(NEW."version", 0) + 1;\n\n            INSERT INTO new_aparts_history (\n                new_apart_id, address, building,\n                building_id, building_code, "number",\n                rooms, "floor", block, area,\n                price, price_m, "type",\n                term_of_application, open_sale, reserve,\n                y2_sell, for_sell, num_on_floor,\n                property, advants, article, \n                price_with_discount, percentage_discount, \n                auction, block_name,\n                created_at, updated_at,\n                "version"\n            )\n            VALUES (\n                NEW.new_apart_id, NEW.address, NEW.building,\n                NEW.building_id, NEW.building_code, NEW."number",\n                NEW.rooms, NEW."floor", NEW.block, NEW.area,\n                NEW.price, NEW.price_m, NEW."type",\n                NEW.term_of_application, NEW.open_sale, NEW.reserve,\n                NEW.y2_sell, NEW.for_sell, NEW.num_on_floor,\n                NEW.property, NEW.advants, NEW.article, \n                NEW.price_with_discount, NEW.percentage_discount, \n                NEW.auction, NEW.block_name,\n                NEW.created_at, NEW.updated_at,\n                NEW."version");\n            RETURN NEW;\n        END;\n        $function$'
    )
    op.create_entity(public_insert_new_aparts_history)

    public_buildings_buildings_history_trigger = PGTrigger(
        schema="public",
        signature="buildings_history_trigger",
        on_entity="public.buildings",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE\n        ON public.buildings\n        FOR EACH ROW\n        EXECUTE FUNCTION public.insert_buildings_history()'
    )
    op.create_entity(public_buildings_buildings_history_trigger)

    public_new_aparts_new_aparts_history_trigger = PGTrigger(
        schema="public",
        signature="new_aparts_history_trigger",
        on_entity="public.new_aparts",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE\n        ON new_aparts\n        FOR EACH ROW  \n        EXECUTE FUNCTION insert_new_aparts_history()'
    )
    op.create_entity(public_new_aparts_new_aparts_history_trigger)

    op.drop_column('buildings_history', 'unique')
    op.drop_column('buildings_temp', 'unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings_temp', sa.Column('unique', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('buildings_history', sa.Column('unique', sa.INTEGER(), autoincrement=False, nullable=True))
    public_new_aparts_new_aparts_history_trigger = PGTrigger(
        schema="public",
        signature="new_aparts_history_trigger",
        on_entity="public.new_aparts",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE\n        ON new_aparts\n        FOR EACH ROW  \n        EXECUTE FUNCTION insert_new_aparts_history()'
    )
    op.drop_entity(public_new_aparts_new_aparts_history_trigger)

    public_buildings_buildings_history_trigger = PGTrigger(
        schema="public",
        signature="buildings_history_trigger",
        on_entity="public.buildings",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE\n        ON public.buildings\n        FOR EACH ROW\n        EXECUTE FUNCTION public.insert_buildings_history()'
    )
    op.drop_entity(public_buildings_buildings_history_trigger)

    public_insert_new_aparts_history = PGFunction(
        schema="public",
        signature="insert_new_aparts_history()",
        definition='RETURNS trigger\n        LANGUAGE plpgsql\n        AS $function$\n        DECLARE \n        BEGIN\n            NEW."version" := COALESCE(NEW."version", 0) + 1;\n\n            INSERT INTO new_aparts_history (\n                new_apart_id, address, building,\n                building_id, building_code, "number",\n                rooms, "floor", block, area,\n                price, price_m, "type",\n                term_of_application, open_sale, reserve,\n                y2_sell, for_sell, num_on_floor,\n                property, advants, article, \n                price_with_discount, percentage_discount, \n                auction, block_name,\n                created_at, updated_at,\n                "version"\n            )\n            VALUES (\n                NEW.new_apart_id, NEW.address, NEW.building,\n                NEW.building_id, NEW.building_code, NEW."number",\n                NEW.rooms, NEW."floor", NEW.block, NEW.area,\n                NEW.price, NEW.price_m, NEW."type",\n                NEW.term_of_application, NEW.open_sale, NEW.reserve,\n                NEW.y2_sell, NEW.for_sell, NEW.num_on_floor,\n                NEW.property, NEW.advants, NEW.article, \n                NEW.price_with_discount, NEW.percentage_discount, \n                NEW.auction, NEW.block_name,\n                NEW.created_at, NEW.updated_at,\n                NEW."version");\n            RETURN NEW;\n        END;\n        $function$'
    )
    op.drop_entity(public_insert_new_aparts_history)

    public_insert_buildings_history = PGFunction(
        schema="public",
        signature="insert_buildings_history()",
        definition='RETURNS trigger\n        LANGUAGE plpgsql\n        AS $function$\n        DECLARE\n        BEGIN\n            NEW."version" := COALESCE(NEW."version", 0) + 1;\n\n            INSERT INTO buildings_history (\n                building_id,    "version",      created_at,\n                updated_at,     address,        code,\n                district,       latitude,       longitude,\n                status_code,    finishing_code, metro,\n                metro_car,      metro_walk,     floors,\n                flats,          vvod,           anons_texts,\n                family_hypotec, county,         notes\n            ) VALUES (\n                NEW.building_id,    NEW."version",      NEW.created_at,\n                NEW.updated_at,     NEW.address,        NEW.code,\n                NEW.district,       NEW.latitude,       NEW.longitude,\n                NEW.status_code,    NEW.finishing_code, NEW.metro,\n                NEW.metro_car,      NEW.metro_walk,     NEW.floors,\n                NEW.flats,          NEW.vvod,           NEW.anons_texts,\n                NEW.family_hypotec, NEW.county,         NEW.notes\n            );\n\n            RETURN NEW;\n        END;\n        $function$'
    )
    op.drop_entity(public_insert_buildings_history)

    # ### end Alembic commands ###
