"""empty message

Revision ID: 27b0aa178977
Revises: 2a8aedd7e8ac
Create Date: 2026-05-17 09:53:41.473922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27b0aa178977'
down_revision: Union[str, Sequence[str], None] = '2a8aedd7e8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building_history', 'soon')
    op.drop_column('building_history', 'gallery')
    op.drop_column('buildings', 'soon')
    op.drop_column('buildings', 'gallery')
    op.drop_column('new_apart_history', 'facing')
    op.drop_column('new_aparts', 'facing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_aparts', sa.Column('facing', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('new_apart_history', sa.Column('facing', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('buildings', sa.Column('gallery', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('buildings', sa.Column('soon', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('building_history', sa.Column('gallery', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('building_history', sa.Column('soon', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
