"""empty message

Revision ID: 4de7b731d320
Revises: 27b0aa178977
Create Date: 2026-05-17 11:10:35.965407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de7b731d320'
down_revision: Union[str, Sequence[str], None] = '27b0aa178977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_apart_history', 'plan')
    op.drop_column('new_apart_history', 'plan_s')
    op.drop_column('new_aparts', 'plan')
    op.drop_column('new_aparts', 'plan_s')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_aparts', sa.Column('plan_s', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('new_aparts', sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('new_apart_history', sa.Column('plan_s', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('new_apart_history', sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
