"""empty message

Revision ID: 58d8c1c1d1d7
Revises: 
Create Date: 2026-05-16 23:16:34.207065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58d8c1c1d1d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_history',
    sa.Column('building_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('district', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('soon', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('finishing_code', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('metro', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metro_car', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metro_walk', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('floors', sa.String(), nullable=True),
    sa.Column('flats', sa.String(), nullable=True),
    sa.Column('vvod', sa.String(), nullable=True),
    sa.Column('unique', sa.Integer(), nullable=True),
    sa.Column('anons_texts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('family_hypotec', sa.Integer(), nullable=False),
    sa.Column('gallery', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('county', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('building_history_id', name=op.f('pk_building_history'))
    )
    op.create_table('buildings',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('district', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('soon', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('finishing_code', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('metro', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metro_car', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metro_walk', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('floors', sa.String(), nullable=True),
    sa.Column('flats', sa.String(), nullable=True),
    sa.Column('vvod', sa.String(), nullable=True),
    sa.Column('unique', sa.Integer(), nullable=True),
    sa.Column('anons_texts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('family_hypotec', sa.Integer(), nullable=False),
    sa.Column('gallery', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('county', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('building_id', name=op.f('pk_buildings'))
    )
    op.create_table('districts',
    sa.Column('district_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('polygons', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('district_id', name=op.f('pk_districts'))
    )
    op.create_table('metros',
    sa.Column('metro_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('metro_id', name=op.f('pk_metros'))
    )
    op.create_table('municipal_districts',
    sa.Column('municipal_district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('polygons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('municipal_district_id', name=op.f('pk_municipal_districts'))
    )
    op.create_table('new_apart_history',
    sa.Column('new_apart_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('new_apart_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('building_code', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('rooms', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=False),
    sa.Column('block', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('price_m', sa.String(), nullable=False),
    sa.Column('plan_s', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('term_of_application', sa.String(), nullable=False),
    sa.Column('open_sale', sa.Integer(), nullable=False),
    sa.Column('reserve', sa.Integer(), nullable=False),
    sa.Column('y2_sell', sa.String(), nullable=False),
    sa.Column('for_sell', sa.String(), nullable=False),
    sa.Column('num_on_floor', sa.String(), nullable=False),
    sa.Column('property', sa.String(), nullable=False),
    sa.Column('advants', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('article', sa.String(), nullable=False),
    sa.Column('price_with_discount', sa.String(), nullable=False),
    sa.Column('percentage_discount', sa.String(), nullable=False),
    sa.Column('facing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auction', sa.String(), nullable=True),
    sa.Column('block_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('new_apart_history_id', name=op.f('pk_new_apart_history'))
    )
    op.create_table('new_aparts',
    sa.Column('new_apart_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('building_code', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('rooms', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=False),
    sa.Column('block', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('price_m', sa.String(), nullable=False),
    sa.Column('plan_s', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('term_of_application', sa.String(), nullable=False),
    sa.Column('open_sale', sa.Integer(), nullable=False),
    sa.Column('reserve', sa.Integer(), nullable=False),
    sa.Column('y2_sell', sa.String(), nullable=False),
    sa.Column('for_sell', sa.String(), nullable=False),
    sa.Column('num_on_floor', sa.String(), nullable=False),
    sa.Column('property', sa.String(), nullable=False),
    sa.Column('advants', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('article', sa.String(), nullable=False),
    sa.Column('price_with_discount', sa.String(), nullable=False),
    sa.Column('percentage_discount', sa.String(), nullable=False),
    sa.Column('facing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auction', sa.String(), nullable=True),
    sa.Column('block_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('new_apart_id', name=op.f('pk_new_aparts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_aparts')
    op.drop_table('new_apart_history')
    op.drop_table('municipal_districts')
    op.drop_table('metros')
    op.drop_table('districts')
    op.drop_table('buildings')
    op.drop_table('building_history')
    # ### end Alembic commands ###
