"""empty message

Revision ID: bdd8b8868e85
Revises: 781b4abbddb4
Create Date: 2026-06-03 13:14:17.882990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd8b8868e85'
down_revision: Union[str, Sequence[str], None] = '781b4abbddb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_aparts', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'building',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'building_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'building_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'rooms',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'floor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'block',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'area',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'price_m',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'term_of_application',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'open_sale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('new_aparts', 'reserve',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('new_aparts', 'y2_sell',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'for_sell',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'num_on_floor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'property',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'article',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'price_with_discount',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts', 'percentage_discount',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'building',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'building_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'building_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'rooms',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'floor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'block',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'area',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'price_m',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'term_of_application',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'open_sale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('new_aparts_history', 'reserve',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('new_aparts_history', 'y2_sell',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'for_sell',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'num_on_floor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'property',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'article',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'price_with_discount',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'percentage_discount',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'building',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'building_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'building_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'rooms',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'floor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'block',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'area',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'price_m',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'term_of_application',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'open_sale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'reserve',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'y2_sell',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'for_sell',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'num_on_floor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'property',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'article',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'price_with_discount',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'percentage_discount',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_aparts_temp', 'percentage_discount',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'price_with_discount',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'article',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'property',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'num_on_floor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'for_sell',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'y2_sell',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'reserve',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'open_sale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'term_of_application',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'price_m',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'area',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'block',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'floor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'rooms',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'building_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'building_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'building',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'percentage_discount',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'price_with_discount',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'article',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'property',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'num_on_floor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'for_sell',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'y2_sell',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'reserve',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('new_aparts_history', 'open_sale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('new_aparts_history', 'term_of_application',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'price_m',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'area',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'block',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'floor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'rooms',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'building_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'building_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'building',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'percentage_discount',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'price_with_discount',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'article',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'property',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'num_on_floor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'for_sell',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'y2_sell',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'reserve',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('new_aparts', 'open_sale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('new_aparts', 'term_of_application',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'price_m',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'area',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'block',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'floor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'rooms',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'building_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'building_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'building',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
