"""empty message

Revision ID: 6f26d58a6965
Revises: 27b0aa178977
Create Date: 2026-05-18 08:34:20.079324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f26d58a6965'
down_revision: Union[str, Sequence[str], None] = '27b0aa178977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings_temp',
    sa.Column('building_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('district', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('finishing_code', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('metro', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metro_car', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metro_walk', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('floors', sa.String(), nullable=True),
    sa.Column('flats', sa.String(), nullable=True),
    sa.Column('vvod', sa.String(), nullable=True),
    sa.Column('unique', sa.Integer(), nullable=True),
    sa.Column('anons_texts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('family_hypotec', sa.Integer(), nullable=False),
    sa.Column('county', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('building_id', name=op.f('pk_buildings_temp'))
    )
    op.create_table('new_apart_temp',
    sa.Column('new_apart_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('building_code', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('rooms', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=False),
    sa.Column('block', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('price_m', sa.String(), nullable=False),
    sa.Column('plan_s', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('term_of_application', sa.String(), nullable=False),
    sa.Column('open_sale', sa.Integer(), nullable=False),
    sa.Column('reserve', sa.Integer(), nullable=False),
    sa.Column('y2_sell', sa.String(), nullable=False),
    sa.Column('for_sell', sa.String(), nullable=False),
    sa.Column('num_on_floor', sa.String(), nullable=False),
    sa.Column('property', sa.String(), nullable=False),
    sa.Column('advants', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('article', sa.String(), nullable=False),
    sa.Column('price_with_discount', sa.String(), nullable=False),
    sa.Column('percentage_discount', sa.String(), nullable=False),
    sa.Column('auction', sa.String(), nullable=True),
    sa.Column('block_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('new_apart_id', name=op.f('pk_new_apart_temp'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_apart_temp')
    op.drop_table('buildings_temp')
    # ### end Alembic commands ###
