"""empty message

Revision ID: 885b671a1083
Revises: df32fe622d08
Create Date: 2026-05-19 22:39:40.550146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885b671a1083'
down_revision: Union[str, Sequence[str], None] = 'df32fe622d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings_temp', 'version')
    op.drop_column('districts', 'version')
    op.drop_column('metros', 'version')
    op.drop_column('municipal_districts', 'version')
    op.drop_column('new_aparts_temp', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_aparts_temp', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('municipal_districts', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('metros', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('districts', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('buildings_temp', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
