"""торги: таблицы лотов недвижимости

Revision ID: c095f0d56de2
Revises: c4e8a7b36d91
Create Date: 2026-10-08 08:51:00.918687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c095f0d56de2'
down_revision: Union[str, Sequence[str], None] = 'c4e8a7b36d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torgi_objects',
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('object_type_code', sa.String(), nullable=True),
    sa.Column('object_type_name', sa.String(), nullable=True),
    sa.Column('tender_type_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('short_address', sa.String(), nullable=True),
    sa.Column('object_address', sa.String(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('district_name', sa.String(), nullable=True),
    sa.Column('unom', sa.Integer(), nullable=True),
    sa.Column('object_area', sa.Numeric(), nullable=True),
    sa.Column('living_area', sa.Numeric(), nullable=True),
    sa.Column('kitchen_area', sa.Numeric(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('room_floor', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('start_price', sa.Numeric(), nullable=True),
    sa.Column('price_per_square', sa.Numeric(), nullable=True),
    sa.Column('request_start_date', sa.DateTime(), nullable=True),
    sa.Column('request_end_date', sa.DateTime(), nullable=True),
    sa.Column('tender_date', sa.DateTime(), nullable=True),
    sa.Column('final_date', sa.DateTime(), nullable=True),
    sa.Column('platform_link', sa.String(), nullable=True),
    sa.Column('torgi_gov_link', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metro', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_text', sa.String(), nullable=True),
    sa.Column('cadastral_number', sa.String(), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('house_type', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('deposit', sa.Numeric(), nullable=True),
    sa.Column('auction_step', sa.Numeric(), nullable=True),
    sa.Column('final_price', sa.Numeric(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('portal_views', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('detail_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('lot_id', name=op.f('pk_torgi_objects'))
    )
    op.create_table('torgi_objects_history',
    sa.Column('torgi_object_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('object_type_code', sa.String(), nullable=True),
    sa.Column('object_type_name', sa.String(), nullable=True),
    sa.Column('tender_type_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('short_address', sa.String(), nullable=True),
    sa.Column('object_address', sa.String(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('district_name', sa.String(), nullable=True),
    sa.Column('unom', sa.Integer(), nullable=True),
    sa.Column('object_area', sa.Numeric(), nullable=True),
    sa.Column('living_area', sa.Numeric(), nullable=True),
    sa.Column('kitchen_area', sa.Numeric(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('room_floor', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('start_price', sa.Numeric(), nullable=True),
    sa.Column('price_per_square', sa.Numeric(), nullable=True),
    sa.Column('request_start_date', sa.DateTime(), nullable=True),
    sa.Column('request_end_date', sa.DateTime(), nullable=True),
    sa.Column('tender_date', sa.DateTime(), nullable=True),
    sa.Column('final_date', sa.DateTime(), nullable=True),
    sa.Column('platform_link', sa.String(), nullable=True),
    sa.Column('torgi_gov_link', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metro', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_text', sa.String(), nullable=True),
    sa.Column('cadastral_number', sa.String(), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('house_type', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('deposit', sa.Numeric(), nullable=True),
    sa.Column('auction_step', sa.Numeric(), nullable=True),
    sa.Column('final_price', sa.Numeric(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('portal_views', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('detail_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('torgi_object_history_id', name=op.f('pk_torgi_objects_history'))
    )
    op.create_table('torgi_objects_temp',
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('object_type_code', sa.String(), nullable=True),
    sa.Column('object_type_name', sa.String(), nullable=True),
    sa.Column('tender_type_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('short_address', sa.String(), nullable=True),
    sa.Column('object_address', sa.String(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('district_name', sa.String(), nullable=True),
    sa.Column('unom', sa.Integer(), nullable=True),
    sa.Column('object_area', sa.Numeric(), nullable=True),
    sa.Column('living_area', sa.Numeric(), nullable=True),
    sa.Column('kitchen_area', sa.Numeric(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('room_floor', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('start_price', sa.Numeric(), nullable=True),
    sa.Column('price_per_square', sa.Numeric(), nullable=True),
    sa.Column('request_start_date', sa.DateTime(), nullable=True),
    sa.Column('request_end_date', sa.DateTime(), nullable=True),
    sa.Column('tender_date', sa.DateTime(), nullable=True),
    sa.Column('final_date', sa.DateTime(), nullable=True),
    sa.Column('platform_link', sa.String(), nullable=True),
    sa.Column('torgi_gov_link', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metro', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_text', sa.String(), nullable=True),
    sa.Column('cadastral_number', sa.String(), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('house_type', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('deposit', sa.Numeric(), nullable=True),
    sa.Column('auction_step', sa.Numeric(), nullable=True),
    sa.Column('final_price', sa.Numeric(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('portal_views', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('detail_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('lot_id', name=op.f('pk_torgi_objects_temp'))
    )
    op.create_table('torgi_object_favorites',
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['torgi_objects.lot_id'], name=op.f('fk_torgi_object_favorites_lot_id_torgi_objects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_torgi_object_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lot_id', 'user_id', name=op.f('pk_torgi_object_favorites'))
    )
    # индексы под выборки списка: тип объекта, статус, район, цена
    op.create_index(
        op.f('ix_torgi_objects_object_type_code'), 'torgi_objects',
        ['object_type_code'], unique=False,
    )
    op.create_index(
        op.f('ix_torgi_objects_status_text'), 'torgi_objects',
        ['status_text'], unique=False,
    )
    op.create_index(
        op.f('ix_torgi_objects_district_name'), 'torgi_objects',
        ['district_name'], unique=False,
    )
    op.create_index(
        op.f('ix_torgi_objects_request_end_date'), 'torgi_objects',
        ['request_end_date'], unique=False,
    )
    op.create_index(
        op.f('ix_torgi_objects_history_lot_id_version'), 'torgi_objects_history',
        ['lot_id', 'version'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_torgi_objects_history_lot_id_version'), table_name='torgi_objects_history'
    )
    op.drop_index(op.f('ix_torgi_objects_request_end_date'), table_name='torgi_objects')
    op.drop_index(op.f('ix_torgi_objects_district_name'), table_name='torgi_objects')
    op.drop_index(op.f('ix_torgi_objects_status_text'), table_name='torgi_objects')
    op.drop_index(op.f('ix_torgi_objects_object_type_code'), table_name='torgi_objects')
    op.drop_table('torgi_object_favorites')
    op.drop_table('torgi_objects_temp')
    op.drop_table('torgi_objects_history')
    op.drop_table('torgi_objects')
    # ### end Alembic commands ###
