"""empty message

Revision ID: be777bc26b69
Revises: 573c1dcf2b76
Create Date: 2026-05-17 12:28:34.495443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be777bc26b69'
down_revision: Union[str, Sequence[str], None] = '573c1dcf2b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building_history', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('building_history', 'img')
    op.alter_column('buildings', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('buildings', 'img')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('buildings', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('building_history', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('building_history', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
