"""empty message

Revision ID: 781b4abbddb4
Revises: 885b671a1083
Create Date: 2026-06-02 16:12:52.787010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781b4abbddb4'
down_revision: Union[str, Sequence[str], None] = '885b671a1083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('buildings', 'unique')
    op.add_column('buildings_history', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('buildings_history', 'unique')
    op.add_column('buildings_temp', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('buildings_temp', 'unique')
    op.add_column('districts', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('metros', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('municipal_districts', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('new_aparts', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('new_aparts_history', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('new_aparts_temp', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_aparts_temp', 'notes')
    op.drop_column('new_aparts_history', 'notes')
    op.drop_column('new_aparts', 'notes')
    op.drop_column('municipal_districts', 'notes')
    op.drop_column('metros', 'notes')
    op.drop_column('districts', 'notes')
    op.add_column('buildings_temp', sa.Column('unique', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('buildings_temp', 'notes')
    op.add_column('buildings_history', sa.Column('unique', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('buildings_history', 'notes')
    op.add_column('buildings', sa.Column('unique', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('buildings', 'notes')
    # ### end Alembic commands ###
