"""empty message

Revision ID: 0c7533763fa2
Revises: bdd8b8868e85
Create Date: 2026-06-03 13:15:56.460618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c7533763fa2'
down_revision: Union[str, Sequence[str], None] = 'bdd8b8868e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_aparts', 'advants',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('new_aparts', 'block_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_history', 'advants',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('new_aparts_history', 'block_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('new_aparts_temp', 'advants',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('new_aparts_temp', 'block_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_aparts_temp', 'block_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_temp', 'advants',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('new_aparts_history', 'block_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts_history', 'advants',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('new_aparts', 'block_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('new_aparts', 'advants',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###
