"""empty message

Revision ID: df32fe622d08
Revises: 2d63f9486493
Create Date: 2026-05-18 16:30:51.713372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df32fe622d08'
down_revision: Union[str, Sequence[str], None] = '2d63f9486493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings_history',
    sa.Column('building_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('district', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('finishing_code', sa.String(), nullable=True),
    sa.Column('metro', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metro_car', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metro_walk', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('floors', sa.String(), nullable=True),
    sa.Column('flats', sa.String(), nullable=True),
    sa.Column('vvod', sa.String(), nullable=True),
    sa.Column('unique', sa.Integer(), nullable=True),
    sa.Column('anons_texts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('family_hypotec', sa.Integer(), nullable=False),
    sa.Column('county', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('building_history_id', name=op.f('pk_buildings_history'))
    )
    op.create_table('new_aparts_history',
    sa.Column('new_apart_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('new_apart_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('building_code', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('rooms', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=False),
    sa.Column('block', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('price_m', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('term_of_application', sa.String(), nullable=False),
    sa.Column('open_sale', sa.Integer(), nullable=False),
    sa.Column('reserve', sa.Integer(), nullable=False),
    sa.Column('y2_sell', sa.String(), nullable=False),
    sa.Column('for_sell', sa.String(), nullable=False),
    sa.Column('num_on_floor', sa.String(), nullable=False),
    sa.Column('property', sa.String(), nullable=False),
    sa.Column('advants', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('article', sa.String(), nullable=False),
    sa.Column('price_with_discount', sa.String(), nullable=False),
    sa.Column('percentage_discount', sa.String(), nullable=False),
    sa.Column('auction', sa.String(), nullable=True),
    sa.Column('block_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('new_apart_history_id', name=op.f('pk_new_aparts_history'))
    )
    op.drop_table('building_history')
    op.drop_table('new_apart_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_apart_history',
    sa.Column('new_apart_history_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('new_apart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('building', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('building_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('building_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rooms', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('floor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('block', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price_m', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('term_of_application', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('open_sale', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reserve', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y2_sell', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('for_sell', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num_on_floor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('property', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('advants', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('article', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price_with_discount', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('percentage_discount', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('auction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('block_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('new_apart_history_id', name=op.f('pk_new_apart_history'))
    )
    op.create_table('building_history',
    sa.Column('building_history_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('district', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('finishing_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metro', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('metro_car', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('metro_walk', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('floors', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('flats', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vvod', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unique', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anons_texts', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('family_hypotec', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('county', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('building_history_id', name=op.f('pk_building_history'))
    )
    op.drop_table('new_aparts_history')
    op.drop_table('buildings_history')
    # ### end Alembic commands ###
