"""empty message

Revision ID: 10d01f2670aa
Revises: 58d8c1c1d1d7
Create Date: 2026-05-17 00:42:02.950662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d01f2670aa'
down_revision: Union[str, Sequence[str], None] = '58d8c1c1d1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building_history', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('buildings', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('districts', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('metros', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('municipal_districts', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('new_apart_history', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('new_aparts', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_aparts', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('new_apart_history', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('municipal_districts', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metros', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('districts', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('buildings', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('building_history', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
