"""empty message

Revision ID: 573c1dcf2b76
Revises: 4de7b731d320
Create Date: 2026-05-17 11:14:08.722193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '573c1dcf2b76'
down_revision: Union[str, Sequence[str], None] = '4de7b731d320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building_history', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('building_history', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('building_history', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('buildings', 'version', server_default='0',
               existing_type=sa.INTEGER(),

               nullable=False)
    op.alter_column('buildings', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('buildings', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('districts', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('districts', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('districts', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('metros', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metros', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('metros', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('municipal_districts', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('municipal_districts', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('municipal_districts', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('new_apart_history', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('new_apart_history', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('new_apart_history', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('new_aparts', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('new_aparts', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('new_aparts', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_aparts', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('new_aparts', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('new_aparts', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('new_apart_history', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('new_apart_history', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('new_apart_history', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('municipal_districts', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('municipal_districts', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('municipal_districts', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('metros', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('metros', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('metros', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('districts', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('districts', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('districts', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('buildings', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('buildings', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('buildings', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('building_history', 'updated_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('building_history', 'created_at',   server_default=sa.func.now(),
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('building_history', 'version', server_default='0',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
